server:
  port: 80
mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  datasource:
    password: root
    url: jdbc:mysql://192.168.31.147:3306/mmm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    host: localhost
    password: root
    port: 5672
    username: root
    virtualHost: /

